# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: reto2021
# app and org for use with dashboard.serverless.com
app: reto2021
org: deimusdark

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    tableNamePersona: Personas
    tableNamePelicula: Pelicula
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:153592805274:table/Personas
        - arn:aws:dynamodb:us-east-1:153592805274:table/Pelicula
plugins:
  - serverless-offline
functions:
  getDatos:
    handler: src/handler.obtenerDatos
    events:
      - httpApi:
          method: GET
          path: /api/reto/{name}/{id}
  getPersona:
    handler: src/Persona/getPersonas.getPersonas
    events:
      - httpApi:
          method: GET
          path: /api/reto/personas
  addPersona:
    handler: src/Persona/addPersona.addPersonaPost
    events:
      - httpApi:
          method: POST
          path: /api/reto/personas
  getPelicula:
    handler: src/Peliculas/getPeliculas.getPeliculas
    events:
      - httpApi:
          method: GET
          path: /api/reto/peliculas
  addPelicula:
    handler: src/Peliculas/addPelicula.addPeliculaPost
    events:
      - httpApi:
          method: POST
          path: /api/reto/peliculas
resources:
  Resources:
    Persona:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Personas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Pelicula:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Pelicula
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH