// this file was generated by serverless-auto-swagger
module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "reto2021",
    "version": "1"
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/api/reto/{name}/{id}": {
      "GET": {
        "summary": "getDatos",
        "description": "",
        "operationId": "getDatos",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/reto/personas": {
      "GET": {
        "summary": "getPersona",
        "description": "",
        "operationId": "getPersona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "POST": {
        "summary": "addPersona",
        "description": "",
        "operationId": "addPersona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/reto/peliculas": {
      "GET": {
        "summary": "getPelicula",
        "description": "",
        "operationId": "getPelicula",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "POST": {
        "summary": "addPelicula",
        "description": "",
        "operationId": "addPelicula",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {}
};